### PR TITLE
[TAS-10] Implement user registration

### PR DESCRIPTION
**Pull request by dickdavis**
This PR adds user registration, a pre-requisite for the OAuth flow which is the end goal of this project. I don't want to waste too much time on registration/authentication, so I'm opting for using Rails' built-in `has_secure_password` functionality. This should speed things up, allowing me to finish setting up a CSP within this app by early next week and then move on to implementing the `authorize` and `callback` endpoints next week.

### Happy Path

* Navigate to root path.
* Click the Sign Up button.
* Fill out the form.
* Click the Sign Up button.
* Open the Rails console and verify the user was created.

### Other things to test

* Verify the field validations are as expected (max length 255 for first_name, last_name, email; all fields required; email must be in valid format, password must match password_confirmation)
* Any field errors should be shown in context of the form field group.
* Any field with errors is clearly identifiable.

<details>
<summary>Screenshots</summary>
<br>

### Home page (Light Mode)
Screenshot 2023-08-11 at 6 59 44 PM

### Home page (Dark Mode)
Screenshot 2023-08-11 at 7 00 12 PM

### Registration page (Light Mode)
Screenshot 2023-08-11 at 8 20 55 PM

### Registration page (Dark Mode)
Screenshot 2023-08-11 at 8 21 19 PM

### Registration page with errors (Light Mode)
Screenshot 2023-08-11 at 8 22 10 PM

### Registration page with errors (Dark Mode)
Screenshot 2023-08-11 at 8 22 33 PM
</details>

### CODE REVIEW

**Comment by bosawt** [comment]
Things look good, can you add a description for how the PR reviewers would test? (Mostly I had issues with getting the server itself running, I have an asset not present error when visiting routes on the server)

**Comment by bosawt** [comment]
Looks good to me, I got the server running, then created an account and can see the record reflected in the database:
image

**Comment by bosawt** [comment]
Had some troubles getting the server up and running the first time so would recommend updating the main README for instructions, but works well once I figured out my issues (mostly with getting `tailwindcss` working on an M1)

**Comment by bramleyjl** [comment]
I'm also having trouble, I'm not seeing anything in my browser when I navigate to `localhost:3000` and no obvious errors:
image


This is what I'm seeing in the console:
```
> bin/dev
10:21:00 web.1  | started with pid 31740
10:21:00 css.1  | started with pid 31741
10:21:01 web.1  | => Booting Puma
10:21:01 web.1  | => Rails 7.0.7 application starting in development 
10:21:01 web.1  | => Run `bin/rails server --help` for more startup options
10:21:01 web.1  | Puma starting in single mode...
10:21:01 web.1  | * Puma version: 5.6.6 (ruby 3.2.2-p53) ("Birdie's Version")
10:21:01 web.1  | *  Min threads: 5
10:21:01 web.1  | *  Max threads: 5
10:21:01 web.1  | *  Environment: development
10:21:01 web.1  | *          PID: 31740
10:21:01 web.1  | * Listening on http://127.0.0.1:3000
10:21:01 web.1  | * Listening on http://[::1]:3000
10:21:01 web.1  | Use Ctrl-C to stop
10:21:02 css.1  | 
10:21:02 css.1  | Rebuilding...
10:21:03 css.1  | 
10:21:03 css.1  | Done in 409ms.
10:21:05 web.1  | Started GET "/" for 127.0.0.1 at 2023-08-15 10:21:05 -0600
10:21:05 web.1  | Processing by HomeController#index as HTML
10:21:05 web.1  |   Rendering layout layouts/application.html.erb
10:21:05 web.1  |   Rendering home/index.html.erb within layouts/application
10:21:05 web.1  |   Rendered home/index.html.erb within layouts/application (Duration: 0.4ms | Allocations: 282)
10:21:05 web.1  |   Rendered layout layouts/application.html.erb (Duration: 42.9ms | Allocations: 51592)
10:21:05 web.1  | Completed 200 OK in 202ms (Views: 44.4ms | ActiveRecord: 0.0ms | Allocations: 332266)
10:21:05 web.1  | 
10:21:05 web.1  | 
```

I had some other small warning in the devtools, that went away when I did the [`force_ruby_platform` change](https://github.com/rails/tailwindcss-rails#check-bundle_force_ruby_platform) you recommended, but didn't affect this, even after a new installation of gems.

Tried on Firefox as well and had the same blank page there.

**Comment by dickdavis** [comment]
@bramleyjl That blank page is all that is on `main` right now. This PR introduces the first bit of functionality (user sign-up). Try fetching the `user-auth` branch and you should see the Sign Up button in the center of the page. If that doesn't fix it, I can hop on a call to help troubleshoot.

**Review by bramleyjl — APPROVED** [review]
Looks good! Earlier issues were indeed due to me being on the `main` branch, in re-testing I was able to create my user and find it in the DB:
```
3.2.2 :001 > User.all
  User Load (0.2ms)  SELECT "users".* FROM "users"
 => 
[#<User:0x00007f29665bf888
  id: 1,
  first_name: "John",
  last_name: "Bramley",
  email: "john.bramley@oddball.io",
  password_digest: "[FILTERED]",
  created_at: Tue, 15 Aug 2023 17:39:25.689461000 UTC +00:00,
  updated_at: Tue, 15 Aug 2023 17:39:25.689461000 UTC +00:00>] 
3.2.2 :002 > 
```

I then started the form again and engaged with the validations; attempted to make another user with the same email, too many characters, mis-matching passwords, etc.

**Pull request merged**
